### ISSUE TITLE
getDicomTarballs password doesn't handle special characters

### ISSUE THREAD

**Issue by AlanKuurstra** [khanlab/neuroglia-helpers#1]
getDicomTarballs prompts for uwo password, but doesn't handle special characters in the password.  for instance, if the password contains &, getDicomTarballs will not handle it correctly.

A current workaround is to start and end the password with quotes when entering.

**Comment by akhanf** [comment]
If this is an issue with backslash I have an easy fix for it?

**Comment by akhanf** [comment]
oops I just realized you opened this in the wrong repo (should be khanlab/autobids), I'll recreate it there
