### ISSUE TITLE
Remove snakemake executable

### ISSUE THREAD

**Issue by pvandyken** [khanlab/neuroglia-helpers#27]
Can we remove the snakemake executable (which activates whatever snakemake is pointed to by `$SNAKEMAKE_VENV_DIR`) and leave `pipx` as the preferred way of installing snakemake? While the current approach has some convenience, it makes configuring a private snakemake more challenging. Notably, pipx becomes impossible, as the neuroglia-helpers executable masks the pipx one. Managing a private version is preferable when control is needed over versioning (especially when developing snakemake itself). The only current work-around is to change `$SNAKEMAKE_VENV_DIR`, which works, but isn't as intuitive or easy as pipx installing.

**Comment by akhanf** [comment]
Yes definitely, I'm good with that.

**Comment by pvandyken** [comment]
Another possibility:
- In `config.yml`, change the value of `cluster: ` to `/path/to/needed/python /full/path/to/slurm-submit.py`. Full paths are needed as snakemake will no longer be able to find our script in the config directory. I haven't tested this solution yet, and I also don't know how to get the `/path/to/needed/python` for e.g. cookiecutter

**Comment by akhanf** [comment]
if we instruct users to use the cookiecutter in pipx's snakemake venv (cookiecutter is in there afaik), then perhaps could be just the current python path?

**Comment by pvandyken** [comment]
Okay, here's something that may work, although I still have to test it in production

```
cluster: '$(cat /proc/$PPID/cmdline | strings -1 | head -n 1) /full/path/to/slurm-submit.py'
```

The reason this works is that for python programs, apparently, the first line of `/proc/$PPID/cmdline` is always the python executable used to run the script, even if that executable was specified in a shebang (I haven't found a resource that explicitly says this is true, but it seems to be based on my experiments). So then all we need is the full path to slurm-submit, which cookiecutter should be able to get

**Comment by akhanf** [comment]
Haha nice find!

**Comment by pvandyken** [comment]
Just tried the `$(cat ...` line, it works great.
